### PR TITLE
tvutil/ntsc: removed need for empty dummy line

### LINKED ISSUE #58: clerLine() needlessly uses VRAM
Said function utilises half an empty line to efficiently generate empty lines during scrolling. This can be handled differently without much penalty (and getting the VRAM back).

 -  draw a line in background colour at the top of the character line
 -  duplicate this line with h/w blitter (avoid <5 transfer widths, **window 9,0,1,20** looked interesting)
 -  the line drawing will have to be accelerated as it's pixel based which introduces a huge overhead

### PR DESCRIPTION
**Pull request by konimaru**
Fixes #58. After working around another h/w bug.

### CODE REVIEW

**Comment by konimaru** [comment]
Had to add **tv_clerLine** to basic_video group like **tv_scroll_down** & Co. Now program load times are back to normal (12sec for _sokoban.bas_ down to 2sec).

**Comment by konimaru** [comment]
What's blocking this from being merged?

If you don't want/like this, OK, but at least tell me!

**Comment by uli** [comment]
It needs to be reviewed, and I haven't found the time to do that because Life etc. That's all there is to it. I'll see that I get around to do it soon.

**Comment by konimaru** [comment]
Perfectly OK, no rush. Take care!

**Comment by uli** [comment]
Had to throw this out again; in the SDL build  clearing doesn't work. Run basic.sdl, then press Ctrl-L and see.

**Comment by uli** [comment]
I also don't know how to set this PR to unmerged again...

**Comment by konimaru** [comment]
How do I get hold of **<SDL/SDL_gfxPrimitives.h>**? IOW, which package(s) do I need to install to have `make sdl` succeed?

**Comment by konimaru** [comment]
From the looks of it, SDL's MoveBlock function doesn't work **vs23s010** style. The latter honors live updates while moving stuff around. SDL simply takes a snapshot of what is there and copies it somewhere else.

I'd argue all platforms should have the same behaviour, in this case following h/w functionality. Your call.

**Pull request merged**
