### PR TITLE
min9 clip

### LINKED ISSUE #49: vs23s010: background window clipping not working
Except for the case when the whole screen can be **completely** covered with tiles, artefacts appear on the right and left hand side. Certain locations on screen will produce vertical bleeding as well. Furthermore, odd-width-tiles are not handled properly although this is a minor issue.

### PR DESCRIPTION
**Pull request by konimaru**
Fixes #49. Minor downside is that the minimum window with is now 9 pixels. I can get it down to 1 but this raises the question of how useful this would be.

### CODE REVIEW

**Comment by uli** [comment]
Cool! I think we can safely ignore the issue with the minimum window size.

Since this is effectively a rewrite of the entire BG drawing code and thus far from a trivial contribution, I would like to ask you to add two things to the patch, though:
1. An overview of how it works, and
2. Your copyright in the license header.

Thank you!

**Comment by konimaru** [comment]
Will do.

**Comment by konimaru** [comment]
Hope this is what you had in mind :)

**Comment by uli** [comment]
Excellent, thanks a lot.

**Pull request merged**
